jdorfman/awesome-json-datasets

- README.md
* Added two new categories
* Closes out #3 & #5
> Added gaming and media

- README.md
> Added Other section

- README.md
* Also fixed italic formatting issue on line 432
> Added 'Help Wanted' to More

- README.md
> Nasa datasets

- CONTRIBUTING.md
I pulled the instructions from my own here https://github.com/machikoyasuda/awesome-fam/blob/master/documentation.md
> Add instructions on running tests from command line

- README.md
> Added Mega Millions Lottery Winning Numbers

- README.md
> Added Chemicals In Cosmetics

- README.md
This json will get the information about GitHub.com
> Add 'meta' in GitHub API section

- README.md
> Add Natural Disasters section with earthquake data

- README.md
> Add Colombia and Venezuela to Population list

- README.md
> Added Australian Government data

- .gitignore
- README.md
For issue #21 
Added Scottish government roles
Added .gitignore file so users running tests don't have to worry about committing the node modules
Removed remaining white space that failed the tests in the past
> Adding Government Roles from the Scottish Parliment API

- README.md
Added Kuala Lumpur, Malaysia weather JSON API.
> add Kuala Lumpur weather

- README.md
Month-wise Progress Report of PMJDY by Public Sectors Banks/Regional Rural Banks/Private Banks upto 2016.PMJDY is a Govt of India scheme holding  Guinness World Record for most bank account opened in 1 week.
> added PMJDY India dataset

- README.md
For issue #21 
- Added Scottish Parliament members
> Adding Scottish Parliament members

- README.md
List of different industries in JSON format
> Add Industries list

- README.md
ISS Current Location
How Many People Are In Space Right Now
> https://github.com/jdorfman/awesome-json-datasets/issues/21

- README.md
> Gross Domestic Product at Current Prices - India

- README.md
Use www.omdbapi.com to generate info on movies based on titles.
> Added movie section with examples

- README.md
Added the number of total players online in Steam under the Gaming category
> Added Steam Player Number

- README.md
TV Shows Added: Friends, HIMYM, Grey's Anatomy.
> Added 3 TV Shows

- README.md
Added New Delhi, Mexico City, Tehran, Mumbai, Cape Town, Madrid, Buenos Aires.
> Added 7 Weather Locations

- README.md
Added dataset for List of dpw maintained street trees including: Planting date, species, and location.
> Added JSON dataset in Govt. Section

- README.md
- SOURCES.md
> adds Gaming: EA Sports FIFA

- README.md
Added a geoJSON dataset for Police Station locations in Victoria, Australia
> Adding VIC Police Station Locations

- README.md
Follows conventions of the other TV Show lists; thought I'd add this great series!
> Add Prison Break episodes to TV Show list

- README.md
Solution: Added links for Nobel Prize data API in JSON format.
It's that time of year again. Here's hoping it's [Murakami's](https://en.wikipedia.org/wiki/Haruki_Murakami) year (we will know tomorrow 🎉).
> Problem: issue #21 addressed for Nobel Prize api

- README.md
#21 
- Added historical events category
- Added two languages under historical events category
> Added historical events category

- README.md
Dataset provides locations for electric vehicle charging stations within the city of Vancouver
> Add Vancouver (Canada) dataset

- README.md
Movies added : PINK and M.S. Dhoni: The Untold Story
> Added movies under Movies

- README.md
Added at topic reddit Linux's subreddit json
> Added Linux Subreddit Data

- README.md
From [football.db](https://github.com/openfootball) - Free open public domain football data in JSON incl. English Premier League, Bundesliga, Primera División, Serie A
> Added Football Clubs and Matches Data

- README.md
> Addition of historical United States Population (since 1960)

- README.md
jService is a dataset of 156,800 trivia questions from the popular TV show jeopardy. At least I think j stands for Jeopardy :) Wasn't sure which category to add it to so I created a new one, Entertainment.
> Adding jService dataset and creating new category entertainment

- README.md
#21 #102 
- Added seven languages in historical events category.
- Added a pro tip in historical events category.
> Added more languages in historical events

- README.md
> Add London Underground Train stations

- README.md
List of 9800+ colleges with name, address, and website
> Added Colleges Data Set

- README.md
Friends added to TV Shows. #21
> Added Friends in TV Shows

- README.md
I put the original list in subsection "Movie Information" for #21
> Added a new subsection "Showtime" in Movies

- README.md
Reverts jdorfman/awesome-json-datasets#127
> Revert "Addition of historical USA GDP since 1960"

- README.md
Added weather for Firenze, Italy.
> Added Firenze to Weather

- README.md
> Add Sunspring to Movies

- README.md
> Add Black Mirror to TV Shows

- README.md
> Add Stranger Things to TV Shows

- README.md
> Add Rick and Morty to TV Shows

- README.md
> Add Steven Universe to TV Shows

- README.md
Movies added-
Kahaani
A Wednesday
Shivaay
Lagaan
Swades
> Added movies under Movies section

- README.md
Added DATA.RALEIGHNC.GOV plus 2 example data sets from the site its self.
> Added DATA.RALEIGHNC.GOV

- README.md
Ensure my/our list is still awesome (part 1) https://github.com/sindresorhus/awesome/issues/926
> Still awesome

- README.md
http://api.fixer.io/ is no longer free. It's now freemium and need access token to get data. This is the good alternative of fixer.io
> add exchangeratesapi

- README.md
👋 @jdorfman, really nice list here 👌
> Remove stray closing parens from 2 entries

- README.md
When requesting the URL I get a status code of 200 but no response content.
> Remove Drought Severity Index from Climate section

- README.md
Some examples picked from https://datos.gob.es/catalogo?res_format_label=JSON
> Added Spanish Government Collections

- README.md
more information at: https://collections.museumvictoria.com.au/developers
> Added Museum Victoria Collections API

- README.md
> Add new link
